simpeg_drivers/joint/__init__.py
simpeg_drivers/joint/joint_surveys/driver.py

**GEOPY-1552 - Crash on joint survey with apparent resistivity**

GEOPY-1552: Crash on joint survey with apparent resistivity

---

simpeg_drivers/joint/__init__.py
simpeg_drivers/joint/joint_surveys/driver.py

**GEOPY-1556 - Fix tile ID on save directive**

GEOPY-1556: Fix tile ID on save directive

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
py-3.10.conda-lock.yml
simpeg_drivers/components/factories/receiver_factory.py
simpeg_drivers/components/factories/source_factory.py
simpeg_drivers/components/models.py
simpeg_drivers/electricals/driver.py
simpeg_drivers/utils/surveys.py
simpeg_drivers/utils/utils.py

**GEOPY-1681 - Streamline geoapps-utils**

GEOPY-1681: Streamline geoapps-utils

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
py-3.10.conda-lock.yml
simpeg_drivers-assets/inversion_demo.geoh5
simpeg_drivers/electricals/driver.py
simpeg_drivers/line_sweep/driver.py

**GEOPY-1690 - merge main to develop after releasing packages for Analayst 4.4.1**

GEOPY-1690: merge main branch (v0.1.1) to develop

---

simpeg_drivers/__init__.py

PATCH-1: Update __init__.py

---

simpeg_drivers/components/factories/entity_factory.py

**GEOPY-1717 - Add docs for validation**

GEOPY-1717: Add docs for validation

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
py-3.10.conda-lock.yml

**GEOPY-1778 - point development to geoh5py release/0.10.0**

GEOPY-1778: relock on tip of develop branches

---

simpeg_drivers/joint/driver.py
simpeg_drivers/joint/joint_cross_gradient/driver.py

**GEOPY-1746 - Review log and out for cross-gradient inversion. **

GEOPY-1746: Review log and out for cross-gradient inversion. 

---

simpeg_drivers/components/models.py
tests/run_tests/driver_dc_2d_test.py
tests/run_tests/driver_mt_test.py

**GEOPY-1818 - Flip upper and lower bound value for resistivity style inversions**

GEOPY-1818: Flip upper and lower bound value for resistivity style inversions

---

simpeg_drivers/utils/utils.py
tests/run_tests/driver_dc_test.py
tests/run_tests/driver_ip_test.py
tests/run_tests/driver_joint_cross_gradient_test.py

**GEOPY-1825 - DC3D inversion reports disconnected cells**

GEOPY-1825: DC3D inversion reports disconnected cells

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
tests/meshes_test.py

**GEOPY-1946 - Octree mesh upside down**

GEOPY-1946: Octree mesh upside down

---

simpeg_drivers/electricals/params.py

**GEOPY-1997 - Crash running 2D IP**

GEOPY-1997: Crash running 2D IP

---

simpeg_drivers/driver.py
tests/run_tests/driver_grav_test.py

**GEOPY-1912 - Add custom Error for problem too large**

GEOPY-1912: Add custom Error for problem too large

---

simpeg_drivers-assets/uijson/direct_current_2d_forward.ui.json
simpeg_drivers-assets/uijson/direct_current_2d_inversion.ui.json
simpeg_drivers-assets/uijson/direct_current_3d_forward.ui.json
simpeg_drivers-assets/uijson/direct_current_3d_inversion.ui.json
simpeg_drivers-assets/uijson/direct_current_batch2d_forward.ui.json
simpeg_drivers-assets/uijson/direct_current_batch2d_inversion.ui.json
simpeg_drivers-assets/uijson/fem_forward.ui.json
simpeg_drivers-assets/uijson/fem_inversion.ui.json
simpeg_drivers-assets/uijson/induced_polarization_2d_forward.ui.json
simpeg_drivers-assets/uijson/induced_polarization_2d_inversion.ui.json
simpeg_drivers-assets/uijson/induced_polarization_3d_forward.ui.json
simpeg_drivers-assets/uijson/induced_polarization_3d_inversion.ui.json
simpeg_drivers-assets/uijson/induced_polarization_batch2d_forward.ui.json
simpeg_drivers-assets/uijson/induced_polarization_batch2d_inversion.ui.json
simpeg_drivers-assets/uijson/magnetotellurics_forward.ui.json
simpeg_drivers-assets/uijson/magnetotellurics_inversion.ui.json
simpeg_drivers-assets/uijson/tdem_forward.ui.json
simpeg_drivers-assets/uijson/tdem_inversion.ui.json
simpeg_drivers-assets/uijson/tipper_forward.ui.json
simpeg_drivers-assets/uijson/tipper_inversion.ui.json
simpeg_drivers/components/factories/simulation_factory.py
simpeg_drivers/params.py
tests/run_tests/driver_airborne_tem_test.py
tests/run_tests/driver_ground_tem_test.py

**GEOPY-1729 - Add option for MUMPS solver**

GEOPY-1729: Add option for MUMPS solver

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
environments/py-3.12-linux-64-dev.conda.lock.yml
environments/py-3.12-linux-64.conda.lock.yml
environments/py-3.12-win-64-dev.conda.lock.yml
environments/py-3.12-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
py-3.12.conda-lock.yml
simpeg_drivers/components/factories/directives_factory.py
simpeg_drivers/components/factories/entity_factory.py
simpeg_drivers/components/factories/simulation_factory.py
simpeg_drivers/utils/testing.py
tests/data_test.py
tests/uijson_test.py

**GEOPY-2025 - Duplicated survey object when monitoring_directory is used**

GEOPY-2025: Duplicated survey object when monitoring_directory is used

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
environments/py-3.12-linux-64-dev.conda.lock.yml
environments/py-3.12-linux-64.conda.lock.yml
environments/py-3.12-win-64-dev.conda.lock.yml
environments/py-3.12-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
py-3.12.conda-lock.yml
simpeg_drivers/components/factories/directives_factory.py
simpeg_drivers/components/factories/entity_factory.py
simpeg_drivers/components/factories/simulation_factory.py
simpeg_drivers/utils/testing.py
tests/data_test.py
tests/uijson_test.py

**GEOPY-2048 - Resolve deprecation warnings with latest simpeg 0.23 and discreatize 0.11**

GEOPY-2048: Resolve deprecation warnings with latest simpeg 0.23 and discreatize 0.11

---

simpeg_drivers/potential_fields/gravity/uijson.py

**GEOPY-2003 - Add UIJson class for gravity forward/inversion**
Patch for default_ui_json paths

GEOPY-2003: Add UIJson class for gravity forward/inversion

---

simpeg_drivers/driver.py
simpeg_drivers/utils/regularization.py
tests/run_tests/driver_rotated_gradients_test.py

**GEOPY-2075 - Implement structural orientation (rotated gradient) option to the inversion UI**

GEOPY-2075: b

---

simpeg_drivers/components/models.py
simpeg_drivers/driver.py
simpeg_drivers/utils/regularization.py

**GEOPY-2075 - Implement structural orientation (rotated gradient) option to the inversion UI**

GEOPY-2075: c

---

simpeg_drivers/components/models.py

**GEOPY-2147 - Name of conductivity_model does not match the selection for resistivity**

GEOPY-2147: Name of conductivity_model does not match the selection for resistivity

---

simpeg_drivers-assets/uijson/direct_current_2d_inversion.ui.json
simpeg_drivers-assets/uijson/direct_current_3d_inversion.ui.json
simpeg_drivers-assets/uijson/direct_current_batch2d_inversion.ui.json
simpeg_drivers-assets/uijson/fem_inversion.ui.json
simpeg_drivers-assets/uijson/gravity_inversion.ui.json
simpeg_drivers-assets/uijson/induced_polarization_2d_inversion.ui.json
simpeg_drivers-assets/uijson/induced_polarization_3d_inversion.ui.json
simpeg_drivers-assets/uijson/induced_polarization_batch2d_inversion.ui.json
simpeg_drivers-assets/uijson/magnetic_scalar_inversion.ui.json
simpeg_drivers-assets/uijson/magnetic_vector_inversion.ui.json
simpeg_drivers-assets/uijson/magnetotellurics_inversion.ui.json
simpeg_drivers-assets/uijson/tdem_inversion.ui.json
simpeg_drivers-assets/uijson/tipper_inversion.ui.json

**GEOPY-2150 - Change default auto-scaling to false**

GEOPY-2150: Change default auto-scaling to false

---

simpeg_drivers/__init__.py

**GEOPY-2154 - MVI name change brakes the forward**

GEOPY-2154: MVI name change brakes the forward

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
environments/py-3.12-linux-64-dev.conda.lock.yml
environments/py-3.12-linux-64.conda.lock.yml
environments/py-3.12-win-64-dev.conda.lock.yml
environments/py-3.12-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
py-3.12.conda-lock.yml
simpeg_drivers-assets/uijson/direct_current_2d_forward.ui.json
simpeg_drivers-assets/uijson/direct_current_2d_inversion.ui.json
simpeg_drivers-assets/uijson/direct_current_batch2d_forward.ui.json
simpeg_drivers-assets/uijson/induced_polarization_2d_forward.ui.json
simpeg_drivers-assets/uijson/induced_polarization_batch2d_forward.ui.json
simpeg_drivers-assets/uijson/induced_polarization_batch2d_inversion.ui.json
simpeg_drivers-assets/uijson/joint_cross_gradient_inversion.ui.json
simpeg_drivers-assets/uijson/joint_petrophysics_inversion.ui.json
simpeg_drivers-assets/uijson/joint_surveys_inversion.ui.json
simpeg_drivers/joint/joint_cross_gradient/options.py
simpeg_drivers/joint/joint_petrophysics/options.py
simpeg_drivers/joint/options.py
simpeg_drivers/line_sweep/driver.py
tests/run_tests/driver_joint_pgi_homogeneous_test.py

**GEOPY-789 - Joint inversion: PGI**

GEOPY-789: Joint inversion: PGI

---

simpeg_drivers-assets/uijson/plate_simulation.ui.json

**GEOPY-2310 - Fix plate simulation label and tooltip**

GEOPY-2310: Fix plate simulation label and tooltip

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
environments/py-3.12-linux-64-dev.conda.lock.yml
environments/py-3.12-linux-64.conda.lock.yml
environments/py-3.12-win-64-dev.conda.lock.yml
environments/py-3.12-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
py-3.12.conda-lock.yml
simpeg_drivers/components/data.py
simpeg_drivers/driver.py
simpeg_drivers/electromagnetics/time_domain/driver.py
simpeg_drivers/utils/tile_estimate.py
simpeg_drivers/utils/utils.py
tests/data_test.py
tests/locations_test.py

**GEOPY-2320 - Investigate slow startup time for TEM inversion**

GEOPY-2320: Investigate slow startup time for TEM inversion

---

.gitignore
pyproject.toml
simpeg_drivers/__init__.py
simpeg_drivers/options.py
simpeg_drivers/uijson.py
tests/uijson_test.py
tests/version_test.py

**GEOPY-2182 - Parallelize 1D simulations**

GEOPY-2182: fixup auto-versioning

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
environments/py-3.12-linux-64-dev.conda.lock.yml
environments/py-3.12-linux-64.conda.lock.yml
environments/py-3.12-win-64-dev.conda.lock.yml
environments/py-3.12-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
py-3.12.conda-lock.yml
simpeg_drivers-assets/uijson/plate_sweep.ui.json
simpeg_drivers/plate_simulation/sweep/driver.py
simpeg_drivers/plate_simulation/sweep/options.py
simpeg_drivers/plate_simulation/uijson.py
tests/plate_simulation/runtest/sweep_test.py

**GEOPY-2457 - Make start/stop group optional, and use the plate-sim parameter instead if disabled**

GEOPY-2457: Make start/stop group optional, and use the plate-sim parameter instead if disabled

---

environments/py-3.10-linux-64-dev.conda.lock.yml
environments/py-3.10-linux-64.conda.lock.yml
environments/py-3.10-win-64-dev.conda.lock.yml
environments/py-3.10-win-64.conda.lock.yml
environments/py-3.11-linux-64-dev.conda.lock.yml
environments/py-3.11-linux-64.conda.lock.yml
environments/py-3.11-win-64-dev.conda.lock.yml
environments/py-3.11-win-64.conda.lock.yml
environments/py-3.12-linux-64-dev.conda.lock.yml
environments/py-3.12-linux-64.conda.lock.yml
environments/py-3.12-win-64-dev.conda.lock.yml
environments/py-3.12-win-64.conda.lock.yml
py-3.10.conda-lock.yml
py-3.11.conda-lock.yml
py-3.12.conda-lock.yml
simpeg_drivers/components/factories/directives_factory.py
simpeg_drivers/joint/driver.py
tests/run_tests/driver_joint_surveys_test.py

**GEOPY-2482 - Missing grouping of EM data in save directive for joint inversions**

GEOPY-2482: Missing grouping of EM data in save directive for joint inversions
